/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendancesystem;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class attendanceViewer extends javax.swing.JFrame {

    /**
     * Creates new form attendanceViewer
     */
    public attendanceViewer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        course = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        studName = new javax.swing.JTextField();
        studIntake = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        studID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Attendace Record"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Start Time", "End Time", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 520, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 570, 630));

        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 180, -1));

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, -1, -1));

        studName.setEditable(false);
        getContentPane().add(studName, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 200, 30));

        studIntake.setEditable(false);
        getContentPane().add(studIntake, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 200, 30));

        jLabel1.setText("Student ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jLabel2.setText("Intake");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, -1));

        jLabel3.setText("Module");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, -1, -1));

        studID.setEditable(false);
        getContentPane().add(studID, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 200, 30));

        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        PopulateComboBox pop = new attendViewComboBox();
        pop.readIntake();
        pop.readCourse();
        pop.populateModule();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        fillTable sa = new studAttend();
        sa.delRows();
        sa.fillRows();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private class attendViewComboBox extends PopulateComboBox {

        @Override
        public String[] readIntake() {
            ArrayList<String> list = new ArrayList<>();
            try {
                searchStudent ss = new searchStudent();
                ss.search(User.currentUser);
                list = ss.getList();
                studID.setText(list.get(0));
                studName.setText(list.get(1) + " " + list.get(2));
                studIntake.setText(list.get(5));
            } catch (IOException ex) {
                Logger.getLogger(attendanceViewer.class.getName()).log(Level.SEVERE, null, ex);
            }
            return list.toArray(new String[list.size()]);
        }

        @Override
        public void populateModule() {

            String lines[];
            lines = readCourse();

            course.removeAllItems();

            for (String str : lines) {
                course.addItem(str);
            }
        }
    }
    
    private class studAttend implements fillTable {
        
        Boolean bool = false;
        @Override
        public void fillTable() {
            System.out.println("printing table");
        }

        @Override
        public void fillRows() {
            String line;
            String intake = studIntake.getText();
            String getCourse = (String) course.getSelectedItem();
            String id = studID.getText();
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            File file = new File("attendancedb.txt");
            /*ArrayList<String> data = new ArrayList<>(); */

            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                //ToDO
                while ((line = br.readLine()) != null) {
                    String[] data = line.split(";");
                    String[] list = {data[0], data[1], data[2], data[7]};
                    if (line.length() > 0 && line.contains(intake) && line.contains(getCourse) && line.contains(id)) {
                        dtm.addRow(list);
                        bool = true;
                    }

                }

            } catch (IOException ex) {
                Logger.getLogger(lecturerManager.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(!bool) {
                JOptionPane.showMessageDialog(null, "No records", "TEST", JOptionPane.ERROR_MESSAGE);
            }
        }

        @Override
        public void delRows() {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int rowCount = dtm.getRowCount();

            for (int i = rowCount - 1; i >= 0; i--) {
                dtm.removeRow(i);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attendanceViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attendanceViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attendanceViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attendanceViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attendanceViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> course;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField studID;
    private javax.swing.JTextField studIntake;
    private javax.swing.JTextField studName;
    // End of variables declaration//GEN-END:variables
}
